name: Run Script

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.0
      with:
        node-version: '21'

    - name: Install dependencies
      run: cd bildchen && yarn

    - name: Run script
      run: cd bildchen && node main.js